import {test,expect} from 'bun:test';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createApp,loadConfig} from '../src/server';import {Store} from '../src/store';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'msgzle-'));const app=createApp({dir,role:'relay',port:0});const config=loadConfig(dir);const call=(path:string,body?:unknown,token=config.token,origin?:string)=>fetch(new URL(path,app.server.url),{method:body?'POST':'GET',headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(origin?{origin}:{})},body:body?JSON.stringify(body):undefined});return {dir,app,config,call,close(){app.close();rmSync(dir,{recursive:true,force:true});}};}
test('auth, fail-closed send policy, origin check, token separation',async()=>{const f=fixture();try{expect((await f.call('/v1/health',undefined,'bad')).status).toBe(401);expect((await f.call('/v1/health',undefined,f.config.token,'https://evil.example')).status).toBe(403);expect((await f.call('/v1/commands',{id:'abcdefgh',to:'+15551234567',text:'hello'})).status).toBe(403);expect((await f.call('/connector/next',{},f.config.token)).status).toBe(401);}finally{f.close();}});
test('command idempotency, conflict, claim-once, no cancellation after attempt',async()=>{const f=fixture();try{await f.call('/admin/config',{sendEnabled:true,recipients:['+15551234567']});const c={id:'abcdefgh',to:'+15551234567',text:'hello'};expect((await f.call('/v1/commands',c)).status).toBe(202);expect((await f.call('/v1/commands',c)).status).toBe(202);expect((await f.call('/v1/commands',{...c,text:'changed'})).status).toBe(400);expect((await (await f.call('/connector/next',{},f.config.connectorToken)).json()).command.id).toBe(c.id);expect((await (await f.call('/connector/next',{},f.config.connectorToken)).json()).command).toBeNull();expect((await (await f.call(`/v1/commands/${c.id}/cancel`,{})).json()).state).toBe('attempting');}finally{f.close();}});
test('restart makes attempting uncertain, never queued again',()=>{const dir=mkdtempSync(join(tmpdir(),'msgzle-'));const path=join(dir,'store.sqlite');let s=new Store(path);s.add({id:'abcdefgh',to:'+15551234567',text:'hello'});s.transition('abcdefgh','queued','attempting');s.close();s=new Store(path);expect(s.get('abcdefgh')?.state).toBe('uncertain');expect(s.next()).toBeUndefined();s.close();rmSync(dir,{recursive:true,force:true});});
test('queued cancellation does not dispatch',async()=>{const f=fixture();try{await f.call('/admin/config',{sendEnabled:true,recipients:['+15551234567']});await f.call('/v1/commands',{id:'abcdefgh',to:'+15551234567',text:'hello'});expect((await (await f.call('/v1/commands/abcdefgh/cancel',{})).json()).state).toBe('cancelled');expect((await (await f.call('/connector/next',{},f.config.connectorToken)).json()).command).toBeNull();}finally{f.close();}});

test('authenticated health includes live allowlist count, not recipients or tokens',async()=>{const f=fixture();try{const health=await (await f.call('/v1/health')).json();expect(health.version).toBe('0.0.2');expect(health.allowlistCount).toBe(0);expect(health.token).toBeUndefined();expect(health.recipients).toBeUndefined();}finally{f.close();}});

test('Everyone is explicit and never bypasses disabled sending or recipient syntax',async()=>{const f=fixture();try{await f.call('/admin/config',{sendEnabled:false,recipients:[],allowEveryone:true});expect((await f.call('/v1/commands',{id:'everyone01',to:'+15551234567',text:'hello'})).status).toBe(403);await f.call('/admin/config',{sendEnabled:true,recipients:[],allowEveryone:true});expect((await f.call('/v1/commands',{id:'everyone02',to:'+15551234567',text:'hello'})).status).toBe(202);expect((await f.call('/v1/commands',{id:'everyone03',to:'*',text:'hello'})).status).toBe(403);expect((await f.call('/admin/config',{sendEnabled:true,recipients:[],retryCap:99})).status).toBe(400);}finally{f.close();}});
